### ISSUE TITLE
Fatal error upon compilation

### ISSUE THREAD

**Issue by jonganej** [figure002/cavendishmw#1] opened 2013-04-17 12:14 UTC
Hi,

Upon clicking on Cavedish MW in the Appearance tab in my Mediawiki, an error surfaces and checking the apache errorlog it gives me the following:

PHP Fatal error:  require_once(): Failed opening required '/Library/WebServer/Documents/mediawiki/skins/CavendishMW.php' (include_path='.:') in /Library/WebServer/Documents/mediawiki/includes/Skin.php on line 167,

I typed in require_once( "$IP/skins/CavendishMW.php" ); into my LocalSettings.php too and  I'm on Mediawiki 1.20..

Thanks

**Comment by figure002** [comment] 2013-07-12 09:46
Thank you for taking the time to report this issue.

I just upgraded to MediaWiki 1.20 and then 1.21.0 and was not able to reproduce your problem. You shouldn't need to include CavendishMW.php in LocalSettings.php, so you can remove the `require_once( "$IP/skins/CavendishMW.php" );` line.

Are you by any chance using system links for the skin files? I do know that that can result in similar errors. And did you put the skin files in the proper location (in the skins/ folder)?

**Comment by figure002** [comment] 2013-07-12 21:25
I just released version 0.3.0 of the skin. Please test this new version. See the README for updated installation instructions.

**Comment by figure002** [comment] 2013-11-06 17:08
Closing this issues because the OP did not report back. Feel free to create a new issue.

**Closed as completed by figure002** 2013-11-06 17:08 UTC

**Comment by kghbln** [comment] 2013-11-20 18:42
I guess the problem was that

<code>require "skins/CavendishMW.php";</code>

was added to call the skin instead of 

<code>require "skins/cavendishmw/CavendishMW.php";</code>

I just tested the skin with 1.21.3 and it works fine. However you still have to call the skin in LocalSettings.php
